parserOptions:
  ecmaVersion: 2017
  sourceType: 'module'
  ecmaFeatures:
    experimentalObjectRestSpread: true

env:
  es6: true
  node: true
  commonjs: true
  browser: false
  mocha: true

extends: 'htmlacademy/node'
